version: '3.8'

services:
  nginx-proxy:
    build: ./nginx
    container_name: main-nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./logs:/var/log/nginx
    networks:
      - app-network

networks:
  app-network:
    driver: bridge