services:
  frontend:
    # build:
    #   context: ./web
    #   args:
    #     VITE_REDIRECT_URL: ${VITE_REDIRECT_URL:-https://172.30.11.52/example}
    image: test-eng-b1-b2-frontend:latest
    ports:
      - "8009:8080"
    environment:
      - API_URL=http://backend:8000
      - API_URL_AI=http://203.150.191.170:4400
      - AI_API_KEY=ai-serviceDtIKlb5a6Fqy9jcKkleyB0cmnN1RVtTt
    depends_on:
      - backend

  backend:
    # build: ./api
    image: test-eng-b1-b2-backend:latest
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=mysql://root:dHfu123!@203.150.191.170:3306/test_prolead
      - EXPORT=7777
      - SECRET_ACCESS_TOKEN_KEY=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
      - SECRET_REFRESH_TOKEN_KEY=dfgdfgsdr
      - EXPIRED_ACCESS_TOKEN=90
      - EXPIRED_REFRESH_TOKEN=10
      - ACCESS_TOKEN_COOKIE_EXPIRED=1
      - NODE_ENV=development
      - USER_ADMIN=admin
      - USER_ADMIN_PASSWORD=admin123
      - PROLEAD_API_URL=http://host.docker.internal:8080

  # revese-proxy:
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx:/etc/nginx/conf.d
  #   ports:
  #     - "4000:80"

  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:4000"]
  #     interval: 1m30s
  #     timeout: 10s
  #     retries: 3
  #   restart: always

networks:
  shared-network:
    external: true
